{{- if .Values.initialAdmin.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "OpenMetadata.fullname" . }}-initial-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "OpenMetadata.labels" . | nindent 4 }}
type: Opaque
data:
  OM_INITIAL_ADMIN_EMAIL: {{ .Values.initialAdmin.email | b64enc | quote }}
  OM_INITIAL_ADMIN_PASSWORD: {{ .Values.initialAdmin.password | b64enc | quote }}
{{- end }}
